name: hire-me/type
table: tx_hireme_type
prefixFields: false
labelField: title
internalDescription: true
hideAtCopy: true
restriction:
  disabled: true
  startTime: true
  endTime: true
  userGroup: true
fields:

  - identifier: title
    type: Text

  - identifier: slug
    required: true
    type: Slug
    eval: uniqueInSite
    generatorOptions:
      fields:
        - title

  - identifier: icon
    type: File
    minitems: 0
    maxitems: 1
    allowed:
      - png
      - jpg
      - jpeg
      - gif
      - webp
    appearance:
      fileUploadAllowed: false
      fileByUrlAllowed: false
