name: hire-me/location
table: tx_hireme_location
prefixFields: false
labelField: street
internalDescription: true
hideAtCopy: true
restriction:
  disabled: true
  startTime: true
  endTime: true
  userGroup: true
security:
  ignorePageTypeRestriction: true
fields:
  - identifier: street # streetAddress
    type: Text

  - identifier: postal_code # postalCode
    type: Text

  - identifier: city # addressLocality
    type: Text

  - identifier: region # addressRegion
    type: Text

  - identifier: country # addressCountry
    type: Select
    renderType: selectSingle
    foreign_table: tx_hireme_country

  - identifier: job_postings
    type: Select
    renderType: selectMultipleSideBySide
    foreign_table: tx_hireme_jobposting
    MM: tx_hireme_jobposting_location_mm
    MM_opposite_field: locations
