name: hire-me/benefit
table: tx_hireme_benefit
prefixFields: false
labelField: title
security:
  ignorePageTypeRestriction: true
fields:
  -
    identifier: title
    type: Text
    label: Title

  - identifier: slug
    required: true
    type: Slug
    eval: uniqueInSite
    generatorOptions:
      fields:
        - title

  - identifier: icon
    type: File
    minitems: 0
    maxitems: 1
    allowed:
      - png
      - jpg
      - jpeg
      - gif
      - webp
    appearance:
      fileUploadAllowed: false
      fileByUrlAllowed: false
