name: hire-me/department
table: tx_hireme_department
prefixFields: false
labelField: title
security:
  ignorePageTypeRestriction: true
fields:
  -
    identifier: title
    type: Text
    label: Title

  - identifier: slug
    required: true
    type: Slug
    eval: uniqueInSite
    generatorOptions:
      fields:
        - title
